### ISSUE TITLE
fails to build with foldl-1.2.2

### ISSUE THREAD

**Issue by juhp** [data61/foldl-statistics#1]
In the Stackage Nightly build:

```
src/Control/Foldl/Statistics.hs:160:31: error:
    Ambiguous occurrence ‘mean’
    It could refer to either ‘Control.Foldl.mean’,
                             imported from ‘Control.Foldl’ at src/Control/Foldl/Statistics.hs:69:1-25
                          or ‘Control.Foldl.Statistics.mean’,
                             defined at src/Control/Foldl/Statistics.hs:118:1
```

**Comment by axman6** [comment]
Thanks Jens, I'll fix that, and set up travis to catch this in the future.

**Comment by axman6** [comment]
@juhp I believe this is now fixed. I'll leave the ticket open until you've confirmed I haven't broken everything. I've enabled stockage too, and it now builds against stackage nightly so this will hopefully not be a problem in the future.

**Comment by juhp** [comment]
Thanks Alex

One new failure:

```
      LinRegState Semigroup:                 FAIL (0.19s)
        *** Failed! Falsifiable (after 28 tests and 23 shrinks): 
        [(-40.96317088163834,0.0),(-23.09878837980997,0.0),(-22.00861641446635,1.0)]
        [(10.277689040163754,0.0),(-32.416612824084986,0.0),(-120.15609657741514,0.822813069381938),(18.047491675541508,0.0),(-5.443624038374302,0.0),(-12.563647685049569,0.0),(-86.81658742129697,0.0)]
        Use --quickcheck-replay '27 TFGenR A822A66AAE1CD18840CD7862FAE2DDEAFF10C72ABECF5388BCE8101E9E9266DB 0 1023 10 0' to reproduce.

1 out of 24 tests failed (0.95s)
```

**Comment by juhp** [comment]
Great, thanks - let me re-enable latest foldl in Nightly then.
